authentication + assign to me
AzDOBridge/azure-devops-bridge pull request #2
Opened 2019-02-18 15:01 UTC by Modarel

2019-02-18 15:12 UTC, wulfland submitted a review, later dismissed

2019-02-20 10:45 UTC, BenjaminAbt requested changes
Please do not directly implement requests into the Controller. Please use an extendable factory like `AzDoBridgeActionFactory`

2019-02-20 10:45 UTC, BenjaminAbt commented on src/AzDoBridge/Controllers/AlexaController.cs
> +                     //Authenticate and maintain User through session
Please do not directory implement intents or launch requests into the controller.
The controller is only a middleware.

Please use a factory like `AzDoBridgeActionFactory`

Maybe we could use the same factory (if names are unique) or we need two factories (one for every Request Type)

2019-02-20 10:45 UTC, BenjaminAbt commented on src/AzDoBridge/Helpers/AADAuthenticator.cs
> +    public static class AADAuthenticator
Please do not use static classes. This is not supported by Dependency Injection.
We should build an extendable and replaceable authentication based on interfaces and dependency-injectionable

2019-02-20 10:45 UTC, BenjaminAbt commented on src/AzDoBridge/Helpers/AADAuthenticator.cs
> +        private static readonly string AUDIENCE = Environment.GetEnvironmentVariable("AzureSecurity:Audience", EnvironmentVariableTarget.Process);
Settings with dependency Injection support please

2019-02-20 10:45 UTC, BenjaminAbt commented on src/AzDoBridge/Helpers/AADAuthenticator.cs
> +            string issuer = ISSUER;
duplicated var

2019-02-20 10:45 UTC, BenjaminAbt commented on src/AzDoBridge/Helpers/AADAuthenticator.cs
> +            while (result == null && tries <= 1)
use a for to avoid the risk of endless loops

2019-02-20 10:45 UTC, BenjaminAbt commented on src/AzDoBridge/Helpers/AADAuthenticator.cs
> +        static async Task<OpenIdConnectConfiguration> GetOpenIDConfig(IConfigurationManager<OpenIdConnectConfiguration> _configurationManager, ILogger log)
no underline in parameter names

2019-02-20 10:45 UTC, BenjaminAbt commented on src/AzDoBridge/Helpers/AADAuthenticator.cs
> +        static async Task<OpenIdConnectConfiguration> GetOpenIDConfig(IConfigurationManager<OpenIdConnectConfiguration> _configurationManager, ILogger log)
logger should be injected, not passed

2019-02-20 10:45 UTC, BenjaminAbt commented on src/AzDoBridge/Helpers/AADAuthenticator.cs
> +                config = await _configurationManager.GetConfigurationAsync(CancellationToken.None);
cancellation should be supported in all of our methods

2019-02-20 10:45 UTC, BenjaminAbt commented on src/AzDoBridge/Helpers/AADAuthenticator.cs
> +            catch (Exception e) { log.LogError($"OpenID Validaiton Exception: {e.Message}"); }
Please no one-liners.

2019-02-25 13:46 UTC, BenjaminAbt commented on src/AzDoBridge/Helpers/AADAuthenticator.cs
> +                Log.LogError($"OpenID Validaiton timeout : {oce.Message}");
Canceled Exception but text says timeout...`?

2019-02-26 15:53 UTC, BenjaminAbt approved these changes

2019-02-26 15:53 UTC, merged